# GitHub Actions workflow for automated macOS builds
# Builds Universal Binary (arm64 + x86_64) VST3 and AU plugins

name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup CMake
      uses: lukka/get-cmake@latest
    
    - name: Verify JUCE submodule
      run: |
        if [ -f "HyperPrismReimagined/JUCE/CMakeLists.txt" ]; then
          echo "✓ JUCE submodule initialized successfully"
        else
          echo "✗ JUCE submodule missing - attempting manual initialization"
          git submodule update --init --recursive
        fi
    
    - name: Configure
      run: |
        cd HyperPrismReimagined
        mkdir build-macos
        cd build-macos
        cmake .. -DCMAKE_BUILD_TYPE=Release \
                 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
    
    - name: Build
      run: |
        cd HyperPrismReimagined/build-macos
        cmake --build . --config Release -j$(sysctl -n hw.ncpu)
    
    - name: Verify Universal Binary
      run: |
        echo "Verifying Universal Binary builds:"
        for vst in HyperPrismReimagined/build-macos/**/VST3/*.vst3; do
          if [ -d "$vst" ]; then
            vst_name=$(basename "$vst" .vst3)
            binary_path="$vst/Contents/MacOS/$vst_name"
            if [ -f "$binary_path" ]; then
              echo "$vst_name: $(lipo -info "$binary_path" 2>/dev/null | cut -d: -f3)"
            fi
          fi
        done
    
    - name: Upload VST3 Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-vst3-plugins
        path: HyperPrismReimagined/build-macos/**/VST3/*.vst3
    
    - name: Upload AU Artifacts (if built)
      uses: actions/upload-artifact@v4
      with:
        name: macos-au-plugins
        path: HyperPrismReimagined/build-macos/**/AU/*.component
      continue-on-error: true # AU might not be built on all configs