# GitHub Actions workflow for automated Windows builds
# Place this in .github/workflows/windows-build.yml in your repo

name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup CMake
      uses: lukka/get-cmake@latest
    
    - name: Verify JUCE submodule
      run: |
        if (Test-Path "HyperPrismReimagined/JUCE/CMakeLists.txt") {
          Write-Host "✓ JUCE submodule initialized successfully"
        } else {
          Write-Host "✗ JUCE submodule missing - attempting manual initialization"
          git submodule update --init --recursive
        }
    
    - name: Configure
      run: |
        cd HyperPrismReimagined
        mkdir build-windows
        cd build-windows
        cmake .. -G "Visual Studio 17 2022" -A x64
    
    - name: Build
      run: |
        cd HyperPrismReimagined/build-windows
        cmake --build . --config Release --parallel
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-vst3-plugins
        path: HyperPrismReimagined/build-windows/*_artefacts/Release/VST3/*.vst3